apiVersion: 1
datasources:
  - name: Mimir
    uid: mimir-uid
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
  - name: Tempo
    uid: tempo-uid
    type: tempo
    access: proxy
    url: http://tempo:3200
  - name: Loki
    uid: loki-uid
    type: loki
    access: proxy
    url: http://loki:3100
