apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server-deployment
  namespace: app
  labels:
    app: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
        - name: express-server-container
          image: express-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              value: "superhackabletestsecret"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: uri
---
# App Service
apiVersion: v1
kind: Service
metadata:
  name: svc-express-server
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: express-server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
# Defines L7 traffic rules with HTTP Route
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: express-server-route
  namespace: app
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: networking
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc-express-server
          namespace: app
          port: 80
