apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server-deployment
  namespace: app
  labels:
    app: express-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
        - name: express-server-container
          image: express-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: JWT_SECRET
              value: "superhackabletestsecret"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: uri
