# Defines L7 traffic rules

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: express-server-route
  namespace: app
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: networking
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: svc-express-server
          namespace: app
          port: 80
