apiVersion: v1
kind: Service
metadata:
  name: svc-express-server
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: express-server
  ports:
    - port: 80 # expose this service on port 80
      targetPort: 3000 # forward to express server port 3000
      protocol: TCP
